### ISSUE TITLE
Image preview in the backend does not display the image correctly 

### ISSUE THREAD

**Issue by fritzdacat** [webcoast-dk/deferred-image-processing#6]
If the extension is installed, when you open an image in the detailed view in the backend, the preview of the image is not displayed correctly. But it was rendered correctly.

**Comment by fritzdacat** [comment]
Just seen, this pull request solves exactly my problem https://github.com/webcoast-dk/deferred-image-processing/pull/2

I just tested it.

The images are displayed correctly again.

Is there a schedule when the pull request will be merged?

Question: Can you somehow switch off the render via the extension in the backend and only use it in the frontend?

**Comment by thommyhh** [comment]
Merged #2 so this should be solved. I will release an official update soon.
