### ISSUE TITLE
Exception for PDFs

### ISSUE THREAD

**Issue by Geddo** [webcoast-dk/deferred-image-processing#7]
Sorry to report another one (already posted that on slack):
- It's not possible to add PDFs to any CE anymore in the Backend (because thumbnail generation fails I guess)
- Frontend also crashes if an PDF is envolved

`(1/1) #1597310560 BadMethodCallException
Width and height of the image must be greater than zero
in /var/www/html/public/typo3/sysext/core/Classes/Imaging/ImageDimension.php line 76`

at $imageDimensions = ImageDimension::fromProcessingTask($task);

Obviously it works when DIP is not active ;-)

**Comment by thommyhh** [comment]
Solved with v1.0.4 by disabling deferred processing for PDF files. Not optimal, but I haven't time for a better solution right now. Will take a look at PDFs again, when I've more time.
